# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    google_credentials_path: '%env(resolve:GOOGLE_AUTH_CONFIG)%'
    google_sheet_id: '%env(GOOGLE_SHEET_ID)%'
    google_sheet_name: '%env(GOOGLE_SHEET_NAME)%'
    chunk_size: '%env(int:CHUNK_SIZE)%'
    source_type : "remote"  #local

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'


    App\Factory\InputParserFactory: ~
    #     arguments:
    #         $credentialsPath: '%kernel.project_dir%/google-credentials.json'

    # Iterator: '@App\Service\XmlStreamIterator'
    # App\Service\XmlStreamIterator:
    #     arguments:
    #         $file: '%kernel.project_dir%/feeds.xml'
            # '%env(FEED_XML_FILE_PATH)%'


    # Bind the interface to the concrete implementation
    App\Service\Contract\FeedProcessorInterface: '@App\Service\FeedProcessorXml'
    
    App\Strategy\XmlParserStrategy:
        arguments:
            $xmlValidator: '@App\Validator\XmlValidator'
            $configValidator: '@App\Validator\ConfigurationValidator'
            $xmlReaderAbstract: '@App\Reader\Xml\XmlGeneratorReader'

    App\Service\FeedProcessorXml:
        arguments:
            $parserFactory: '@App\Factory\InputParserFactory'
            $googleSheetsService: '@App\Service\GoogleSheetsService'
            $logger: '@logger'
            $configValidator: '@App\Validator\ConfigurationValidator'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
